export const TRACKEDEXTENSION = [
    // ---------- Programming Languages ----------
    '.js', '.mjs', '.cjs',
    '.ts', '.tsx', '.jsx',
    '.py',
    '.java',
    '.c', '.h',
    '.cpp', '.cc', '.cxx', '.hpp',
    '.cs',
    '.go',
    '.rs',
    '.rb',
    '.php',
    '.swift',
    '.kt', '.kts',
    '.scala',
    '.dart',
    '.r',
    '.jl',
    '.lua',
    '.pl',
    '.sh', '.bash',
    '.ps1',
    '.asm', '.s',
    '.f', '.f90',
    '.cob',
    '.groovy',
    '.hs',
    '.ex', '.exs',
    '.fs', '.fsi', '.fsx',
    '.clj', '.cljs', '.cljc',
    '.lisp', '.el',
    '.nim',
    '.zig',
    '.v',
    '.sol',
    '.gd',
    '.ada', '.adb', '.ads',
    '.ml', '.mli',
    '.cr',
    '.pony',
    '.awk',
    '.pro',
    '.tcl',
    '.rkt',
    '.e',
    '.smalltalk',

    // ---------- Markup / Markdown / Data ----------
    '.html', '.htm',
    '.xml',
    '.md', '.markdown',
    '.mdx',
    '.rst',
    '.adoc',
    '.tex',
    '.bib',
    '.yml', '.yaml',
    '.json',
    '.jsonc',
    '.toml',
    '.ini',
    '.cfg',
    '.csv',
    '.tsv',
    '.svg',
    '.xhtml',
    '.xaml',
    '.opml',
    '.org',
    '.wiki',
    '.txt',

    // ---------- Styling / UI / Design ----------
    '.css',
    '.scss',
    '.sass',
    '.less',
    '.styl',
    '.pcss',
    '.postcss',
    '.tailwind.css',
    '.module.css',
    '.module.scss',

    // ---------- Mobile / UI Framework Styling ----------
    // '.qml',
    // '.ux',
    // '.themes',
    // '.tokens.json',
];
